version: '3'
services:
  
  web:
    image: nginx:alpine
    volumes:
      - "./web:/var/www/html"
      - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"            
      - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
#     - "./etc/ssl:/etc/ssl"
    ports:
      - "8000:80"
      - "3000:443"
    environment:
      - NGINX_HOST=${NGINX_HOST}
    command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always
    depends_on:
      - php
      - db

  composer:
#   image: composer/composer:php7
    image: "composer"
    command: install
    volumes:
      - "./web/app:/app"

  php:
    image: php:7-fpm
    volumes:
      - "./web:/var/www/html"
      - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
    ports:
      - "9000:9000"
    depends_on:
      - db

  db:
    image: mariadb:latest
    volumes:
      - ./mysql:/var/lib/mysql